Testing environment, Citizens, Organizations, Users
aau-giraf/weekplanner-api pull request #100
Opened 2024-11-15 13:40 UTC by PixieStick314

## Description
Seeders for Citizens, Organizations, and Users have been created, the latter of which has null errors at the moment.
Tests for all three have been written as well, although due to the 'null' issues with users, there are 6 of them that fail.
I've had to add a checker for environment in the Program.cs file, so that the ApplyMigrationsAsync don't auto-apply.

## Related issues
#80

## Checklist
- [X] My code is in the right place.\
- [X] My code fully addresses the issue I was working on.\
- [X] I have added appropriate tests and error handling.\
- [] My code follows the style guidelines.\
- [X] I have added relevant comments explaining the purpose and function of my code (if necessary).\
- [] I have added relevant documentation to the GitHub wiki.\
- [X] I have created a pull request and notified the teams.

2024-11-15 13:53 UTC, JEEEEENS21 submitted a review, later dismissed

2024-11-15 14:52 UTC, MertzAndreas requested changes
Personally not a fan of getting failing tests into main

2024-11-20 11:19 UTC, Tbjerregaard approved these changes

2024-11-20 14:23 UTC, Tbjerregaard approved these changes

2024-11-20 16:05 UTC, JEEEEENS21 approved these changes

2024-11-20 16:08 UTC, merged