Updated Copy Activities
aau-giraf/weekplanner-api pull request #138
Opened 2024-12-07 16:27 UTC by Stoldt

## Description
Changed the copy-Activities endpoint
Added an endpoint to copy activities for grades

## Related issues
None

## Checklist
- [x] My code is in the right place.\
- [x] My code fully addresses the issue I was working on.\
- [ ] I have added appropriate tests and error handling.\
- [x] My code follows the style guidelines.\
- [x] I have added relevant comments explaining the purpose and function of my code (if necessary).\
- [ ] I have added relevant documentation to the GitHub wiki.\
- [x] I have created a pull request and notified the teams.

2024-12-07 17:15 UTC, Simo205j approved these changes
![giphy](https://github.com/user-attachments/assets/9437a1dc-4640-4f5a-84e7-33c6f2789ddd)

2024-12-07 20:22 UTC, LokeSGJ requested changes
Kunne jeg få dig til at committe den uden den nye migration? Den burde ikke være nødvendig, for du har ikke ændret på nogen af vores datamodeller

2024-12-09 13:19 UTC, LokeSGJ approved these changes

2024-12-09 13:20 UTC, DanielRBech approved these changes

2024-12-09 13:20 UTC, merged